
apiVersion: v1
kind: Service
metadata:
  name: jenkinsserver
  labels:
    app: jenkins
    #tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: jenkins
    #tier: frontend
