kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pan-crole
rules:
- apiGroups: ["*"]
  resources: ["secrets", "certificatesigningrequests", "certificatesigningrequests/approval", "certificatesigningrequests/status"]
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  - endpoints
  verbs:
  - get
