
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - services
  - secrets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plugin-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plugin-cluster-role
subjects:
- kind: ServiceAccount
  name: plugin-user
  namespace: kube-system
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: plugin-user
  namespace: kube-system